import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { sendEmail } from "@/lib/brevo";

const MAX_EMPLOYEES = 5;
const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://www.stampify.ch";

export async function POST(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Non authentifié" }, { status: 401 });

  // Verify business owner + Pro plan
  const { data: business } = await supabase
    .from("businesses")
    .select("business_name, plan, subscription_status")
    .eq("id", user.id)
    .single();

  if (!business) return NextResponse.json({ error: "Commerce introuvable" }, { status: 404 });
  if (business.plan !== "pro" || business.subscription_status !== "active") {
    return NextResponse.json({ error: "Cette fonctionnalité requiert le plan Pro." }, { status: 403 });
  }

  // Check employee count
  const { count } = await supabase
    .from("employees")
    .select("id", { count: "exact", head: true })
    .eq("business_id", user.id);

  if ((count ?? 0) >= MAX_EMPLOYEES) {
    return NextResponse.json({ error: `Maximum ${MAX_EMPLOYEES} employés atteint.` }, { status: 422 });
  }

  const { email, name } = await req.json() as { email: string; name: string };
  if (!email || !name) return NextResponse.json({ error: "email et name requis" }, { status: 400 });

  // Insert employee row (invite_token generated by DB default)
  const { data: employee, error: insertError } = await supabase
    .from("employees")
    .insert({ business_id: user.id, email: email.toLowerCase().trim(), name: name.trim() })
    .select("invite_token, name")
    .single();

  if (insertError) {
    const msg = insertError.code === "23505"
      ? "Cet employé est déjà invité."
      : insertError.message;
    return NextResponse.json({ error: msg }, { status: 422 });
  }

  const inviteUrl = `${APP_URL}/employee/join?token=${employee.invite_token}`;

  // Send invitation email (fire-and-forget)
  sendEmail(
    email,
    `Invitation à rejoindre ${business.business_name} sur Stampify`,
    `
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto">
      <div style="background:#534AB7;padding:24px;text-align:center">
        <h1 style="color:white;margin:0;font-size:24px">Stampify</h1>
      </div>
      <div style="padding:32px">
        <h2 style="color:#111827">Bonjour ${employee.name},</h2>
        <p style="color:#374151">Vous avez été invité(e) à rejoindre
          <strong>${business.business_name}</strong>
          en tant qu'employé(e) sur Stampify.</p>
        <p style="color:#374151">Cliquez sur le bouton ci-dessous pour créer votre compte :</p>
        <div style="text-align:center;margin:32px 0">
          <a href="${inviteUrl}"
             style="background:#534AB7;color:white;padding:14px 32px;border-radius:10px;
                    text-decoration:none;font-weight:bold;display:inline-block">
            Accepter l'invitation
          </a>
        </div>
        <p style="color:#9ca3af;font-size:13px">Ce lien est à usage unique.</p>
      </div>
    </div>`
  ).catch(console.error);

  return NextResponse.json({ success: true, inviteUrl });
}
